# Generated by Django 5.0.6 on 2024-07-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviewMode',
            new_name='reviewModel',
        ),
    ]
